# Generated by Django 3.2.8 on 2021-10-28 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.CharField(max_length=100)),
                ('display_contact', models.CharField(max_length=100)),
                ('display_company', models.CharField(max_length=100)),
                ('plan_selected', models.CharField(max_length=50)),
                ('is_accepted', models.BooleanField(default=False)),
                ('profession', models.CharField(max_length=100)),
                ('business_established', models.CharField(max_length=4)),
                ('business_location', models.CharField(max_length=50)),
                ('interested_in', models.CharField(max_length=50)),
                ('no_employees', models.PositiveBigIntegerField()),
                ('describe', models.TextField()),
                ('highlights', models.TextField()),
                ('product_list', models.TextField()),
                ('facility', models.TextField()),
                ('monthly_sales', models.PositiveBigIntegerField()),
                ('yearly_sales', models.PositiveBigIntegerField()),
                ('ebitda', models.CharField(max_length=5)),
                ('assets', models.TextField()),
                ('physical_assets', models.TextField()),
                ('photos', models.FileField(upload_to='photoimg')),
                ('docs', models.FileField(upload_to='doc')),
                ('proof', models.FileField(upload_to='proof_docs')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('isVerified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forget_password_token', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
