# Generated by Django 3.2.8 on 2021-10-29 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.CharField(max_length=100, null=True)),
                ('display_contact', models.CharField(max_length=100, null=True)),
                ('display_company', models.CharField(max_length=100, null=True)),
                ('plan_selected', models.CharField(max_length=50, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('profession', models.CharField(max_length=100, null=True)),
                ('business_established', models.CharField(default='', max_length=4)),
                ('business_location', models.CharField(max_length=50, null=True)),
                ('interested_in', models.CharField(max_length=50, null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('no_employees', models.PositiveBigIntegerField(default=0)),
                ('legal', models.CharField(max_length=100, null=True)),
                ('describe', models.TextField(null=True)),
                ('describe_new', models.TextField(null=True)),
                ('highlights', models.TextField(null=True)),
                ('product_list', models.TextField(null=True)),
                ('facility', models.TextField(null=True)),
                ('monthly_sales', models.PositiveBigIntegerField(default=0)),
                ('yearly_sales', models.PositiveBigIntegerField(default=0)),
                ('ebitda', models.CharField(max_length=5, null=True)),
                ('assets', models.TextField(null=True)),
                ('physical_assets', models.TextField(default='')),
                ('photos', models.FileField(upload_to='photoimg')),
                ('docs', models.FileField(upload_to='doc')),
                ('proof', models.FileField(upload_to='proof_docs')),
            ],
        ),
    ]
