# Generated by Django 3.2.8 on 2021-10-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='mobile_number',
        ),
    ]
