# Generated by Django 3.2.8 on 2021-10-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='profile_status',
            field=models.CharField(choices=[('Acccepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
