# Generated by Django 3.2.8 on 2021-10-29 20:16

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0002_businessprofile_profile_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='businessprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
