# Generated by Django 3.2.8 on 2021-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0002_remove_businessprofile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='assets',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='describe',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='describe_new',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='display_company',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='display_contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='ebitda',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='facility',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='highlights',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='interested_in',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='legal',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='monthly_sales',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='no_employees',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='plan_selected',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='product_list',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='yearly_sales',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
