# Generated by Django 3.2.8 on 2021-10-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0003_alter_businessprofile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='businessprofile',
            managers=[
            ],
        ),
    ]
