# Generated by Django 3.2.8 on 2021-10-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0003_auto_20211020_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
