# Generated by Django 3.2.8 on 2021-10-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0003_auto_20211029_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
