# Generated by Django 3.2.8 on 2021-10-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0004_alter_businessprofile_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='profile_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
