# Generated by Django 3.2.8 on 2021-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0004_alter_businessprofile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_established',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
