# Generated by Django 3.2.8 on 2021-10-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0005_auto_20211029_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='doc'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='photoimg'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='physical_assets',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proof_docs'),
        ),
    ]
