# Generated by Django 3.2.8 on 2021-10-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0005_alter_businessprofile_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentprofile',
            name='profile_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
